### ISSUE TITLE
problem with compling

### ISSUE THREAD

**Issue by Giaitzoglou** [munichmakerlab/light-duino#2]
hi i tried to comple it and i always get this error.
Arduino: 1.8.5 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 4M (1M SPIFFS), ck, Disabled, None"

C:\Users\Chris\Documents\Arduino\light-duino\light-duino.ino: In function 'void setupWifi()':

light-duino:160: error: invalid conversion from 'void (*)()' to 'void (*)(WiFiManager*)' [-fpermissive]

     wifiManager.setAPCallback(configModeCallback);

                                                 ^

In file included from C:\........Documents\Arduino\light-duino\light-duino.ino:21:0:

C:\.......Arduino\libraries\WiFiManager/WiFiManager.h:92:19: error:   initializing argument 1 of 'void WiFiManager::setAPCallback(void (*)(WiFiManager*))' [-fpermissive]

     void          setAPCallback( void (*func)(WiFiManager*) );

                   ^

light-duino:164: error: 'class WiFiManager' has no member named 'setAPConfig'

     wifiManager.setAPConfig(IPAddress(10,0,0,1), IPAddress(10,0,0,1), IPAddress(255,255,255,0));

                 ^

exit status 1
invalid conversion from 'void (*)()' to 'void (*)(WiFiManager*)' [-fpermissive]

can you please help to make work?
thank chris

**Comment by tiefpunkt** [comment]
Change line 102 to `void configModeCallback (WiFiManager* myWiFiManager) {` to fix the first and second problem.

And line 164 should be `wifiManager.setAPStaticIPConfig(IPAddress(10,0,0,1), IPAddress(10,0,0,1), IPAddress(255,255,255,0));`

This was just eyeballing it from recent docs, this is somewhat older code, and I haven't touched it in ages, but it looks like we used a different version of wifiManager than in use today. If the fixes above seem to work, please put in a pull request so those changes are reflected in the repo as well :)

**Comment by Giaitzoglou** [comment]
Hi do you have a more recent library what I want is just to send via mqtt command to turn a dmx dimmer light brighter or darker . That for the only thing I want it 
Do you have any suggestions ? 
Thanks 
Chris

**Comment by Giaitzoglou** [comment]
hi thanks for your help now i get this as you see i am a rookie with coding thanks for your help.
Arduino: 1.8.5 (Windows 10), Board: "WeMos D1 R2 & mini, 80 MHz, 921600, 4M (3M SPIFFS)"

C:\Users\\Documents\Arduino\light-duino\light-duino.ino: In function 'void setupWifi()':

light-duino:163: error: expected initializer before 'wifiManager'

  wifiManager.setAPStaticIPConfig(IPAddress(10,0,0,1), IPAddress(10,0,0,1), IPAddress(255,255,255,0));    //and goes into a blocking loop awaiting configuration

  ^

exit status 1
expected initializer before 'wifiManager'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
