### ISSUE TITLE
DMX SONOFF MAX-485

### ISSUE THREAD

**Issue by arnaud-aub** [munichmakerlab/light-duino#4]
J'éssaye de contrôler des lumières DMX via wifi à l'aide de sonoff, MAX-485 et prises DMX.

**Comment by arnaud-aub** [comment]
Bonjour, je voudrais savoir s'il y avait possibilité de m'aider, je ne sais pas comment contrôler mes lumières avec un Sonoff, il me semble que le GPIO2 n'est pas accessible, comment puis-je faire ?

**Comment by tiefpunkt** [comment]
Not sure if google translate did a proper job here. This uses https://github.com/Rickgg/ESP-Dmx for the DMX part, which in turn uses Serial1 as its output. I'm not aware of changing that to a different pin, so if GPIO2 is not accessible for you, then this code here won't work for you unfortunately.

You could try connecting a write directly to the GPIO2 pin on the actual ESP8266 chip in the sonoff, but that's probably quite risky.
